-- =======================
-- 💥 테이블 삭제 💥(주의)
-- =======================

-- DROP TABLE IF EXISTS `CLOSING_PRICE`;
-- DROP TABLE IF EXISTS `TRADE`;
-- DROP TABLE IF EXISTS `ORDER`;
-- DROP TABLE IF EXISTS `USER_COIN`;
-- DROP TABLE IF EXISTS `COIN`;
-- DROP TABLE IF EXISTS `CAREER`;
-- DROP TABLE IF EXISTS `EDUCATION`;
-- DROP TABLE IF EXISTS `CERTIFICATION`;
-- DROP TABLE IF EXISTS `USER_SKILL`;
-- DROP TABLE IF EXISTS `SKILL`;
-- DROP TABLE IF EXISTS `PROFILE`;
-- DROP TABLE IF EXISTS `USER`;

-- =======================
-- 🔨 테이블 생성
-- =======================

-- USER
CREATE TABLE IF NOT EXISTS `USER` (
	`USER_ID` VARCHAR(50) NOT NULL,
	`NAME` VARCHAR(50) NULL,
	`EMAIL` VARCHAR(50) NULL,
	`USERNAME` VARCHAR(50) NULL,
	`PWD` VARCHAR(255) NULL,
	`IMAGE` VARCHAR(255) NULL,
	`MONEY` DECIMAL(15, 2) NULL,
	`CREATED_AT` DATETIME NULL,
	`UPDATED_AT` DATETIME NULL,
	PRIMARY KEY (`USER_ID`),
	UNIQUE KEY `UK_USER_USERNAME` (`USERNAME`)
);
-- PROFILE
CREATE TABLE IF NOT EXISTS `PROFILE` (
	`USER_ID` VARCHAR(50) NOT NULL,
	`POSITION` VARCHAR(50) NULL,
	`BIO` VARCHAR(100) NULL,
	`GITHUB` VARCHAR(255) NULL,
	`BLOG` VARCHAR(255) NULL,
	`SNS` VARCHAR(255) NULL,
    `LINKEDIN` VARCHAR(255) NULL,
	`RESUME` VARCHAR(255) NULL,
	`CREATED_AT` DATETIME NULL,
	`UPDATED_AT` DATETIME NULL,
	PRIMARY KEY (`USER_ID`),
	FOREIGN KEY (`USER_ID`) REFERENCES `USER`(`USER_ID`) ON DELETE CASCADE
);
-- SKILL
CREATE TABLE IF NOT EXISTS `SKILL` (
	`SKILL_ID` VARCHAR(50) NOT NULL,
	`STACK` VARCHAR(255) NULL,
	`CREATED_AT` DATETIME NULL,
	`UPDATED_AT` DATETIME NULL,
	PRIMARY KEY (`SKILL_ID`)
);
-- USER_SKILL
CREATE TABLE IF NOT EXISTS `USER_SKILL` (
    `USER_ID` VARCHAR(50) NOT NULL,
	`SKILL_ID` VARCHAR(50) NOT NULL,
	`CREATED_AT` DATETIME NULL,
	`UPDATED_AT` DATETIME NULL,
	PRIMARY KEY (`USER_ID`, `SKILL_ID`),
	FOREIGN KEY (`USER_ID`) REFERENCES `USER`(`USER_ID`) ON DELETE CASCADE,
    FOREIGN KEY (`SKILL_ID`) REFERENCES `SKILL`(`SKILL_ID`) ON DELETE CASCADE
);
-- CERTIFICATION
CREATE TABLE IF NOT EXISTS `CERTIFICATION` (
	`CERTIFICATION_ID` VARCHAR(50) NOT NULL,
	`USER_ID` VARCHAR(50) NOT NULL,
	`CERTIFICATE_URL` VARCHAR(255) NULL,
	`CREATED_AT` DATETIME NULL,
	`UPDATED_AT` DATETIME NULL,
	PRIMARY KEY (`CERTIFICATION_ID`),
	FOREIGN KEY (`USER_ID`) REFERENCES `USER`(`USER_ID`) ON DELETE CASCADE
);
-- EDUCATION
CREATE TABLE IF NOT EXISTS `EDUCATION` (
	`EDUCATION_ID` VARCHAR(50) NOT NULL,
	`USER_ID` VARCHAR(50) NOT NULL,
	`SCHOOL_NAME` VARCHAR(20) NULL,
	`STATUS` ENUM('ENROLLED', 'GRADUATED') NULL,
	`MAJOR` VARCHAR(100) NULL,
	`START_DATE` DATE NULL,
	`END_DATE` DATE NULL,
	`CERTIFICATE_URL` VARCHAR(255) NULL,
	`CREATED_AT` DATETIME NULL,
	`UPDATED_AT` DATETIME NULL,
	PRIMARY KEY (`EDUCATION_ID`),
	FOREIGN KEY (`USER_ID`) REFERENCES `USER`(`USER_ID`) ON DELETE CASCADE
);
-- CAREER
CREATE TABLE IF NOT EXISTS `CAREER` (
	`CAREER_ID` VARCHAR(50) NOT NULL,
	`USER_ID` VARCHAR(50) NOT NULL,
	`COMPANY_NAME` VARCHAR(50) NULL,
	`STATUS` ENUM('EMPLOYED','NOT_EMPLOYED') NULL,
	`POSITION` VARCHAR(50) NULL,
	`START_DATE` DATE NULL,
	`END_DATE` DATE NULL,
	`CERTIFICATE_URL` VARCHAR(255) NULL,
	`CREATED_AT` DATETIME NULL,
	`UPDATED_AT` DATETIME NULL,
	PRIMARY KEY (`CAREER_ID`),
	FOREIGN KEY (`USER_ID`) REFERENCES `USER`(`USER_ID`) ON DELETE CASCADE
);
-- COIN
CREATE TABLE IF NOT EXISTS `COIN` (
	`COIN_ID` VARCHAR(50) NOT NULL,
    `CREATOR_ID` VARCHAR(50) NULL,
    `CURRENT_PRICE` DECIMAL(15, 2) NULL,
    `CLOSING_PRICE` DECIMAL(15, 2) NULL,
    `CREATED_AT` DATETIME NULL,
	`UPDATED_AT` DATETIME NULL,
	PRIMARY KEY (`COIN_ID`),
    FOREIGN KEY (`CREATOR_ID`) REFERENCES `USER`(`USER_ID`) ON DELETE SET NULL
); 
-- USER_COIN
CREATE TABLE IF NOT EXISTS `USER_COIN` (
	`USER_COIN_ID` VARCHAR(50) NOT NULL,
	`HOLDER_ID` VARCHAR(50) NOT NULL,
	`COIN_ID` VARCHAR(50) NOT NULL,
	`HOLD_QUANTITY` DECIMAL(15, 2) NULL,
	`TOTAL_BUY_AMOUNT` DECIMAL(15, 2) NULL,
    `CREATED_AT` DATETIME NULL,
	`UPDATED_AT` DATETIME NULL,
	PRIMARY KEY (`USER_COIN_ID`),
	FOREIGN KEY (`HOLDER_ID`) REFERENCES `USER`(`USER_ID`) ON DELETE CASCADE,
	FOREIGN KEY (`COIN_ID`) REFERENCES `COIN`(`COIN_ID`) ON DELETE CASCADE
);
-- ORDER
CREATE TABLE IF NOT EXISTS `ORDER` (
	`ORDER_ID` VARCHAR(50) NOT NULL,
	`USER_ID` VARCHAR(50) NOT NULL,
	`COIN_ID` VARCHAR(50) NOT NULL,
	`ORDER_TYPE` ENUM('BUY', 'SELL') NULL,
	`QUANTITY` DECIMAL(15, 2) NULL,
	`UNIT_PRICE` DECIMAL(15, 2) NULL,
	`CREATED_AT` DATETIME NULL,
	`UPDATED_AT` DATETIME NULL,
	PRIMARY KEY (`ORDER_ID`),
	FOREIGN KEY (`USER_ID`) REFERENCES `USER`(`USER_ID`),
	FOREIGN KEY (`COIN_ID`) REFERENCES `COIN`(`COIN_ID`)
);
-- TRADE
CREATE TABLE IF NOT EXISTS `TRADE` (
	`TRADE_ID` VARCHAR(50) NOT NULL,
	`COIN_ID` VARCHAR(50) NOT NULL,
    `SELL_USER_ID` VARCHAR(50) NOT NULL,
    `BUY_USER_ID` VARCHAR(50) NOT NULL,
	`QUANTITY` DECIMAL(15, 2) NULL,
	`UNIT_PRICE` DECIMAL(15, 2) NULL,
	`CREATED_AT` DATETIME NULL,
	`UPDATED_AT` DATETIME NULL,
	PRIMARY KEY (`TRADE_ID`),
	FOREIGN KEY (`COIN_ID`) REFERENCES `COIN`(`COIN_ID`),
    FOREIGN KEY (`SELL_USER_ID`) REFERENCES `USER`(`USER_ID`),
    FOREIGN KEY (`BUY_USER_ID`) REFERENCES `USER`(`USER_ID`)
);
-- CLOSING_PRICE
CREATE TABLE IF NOT EXISTS `CLOSING_PRICE` (
	`CLOSING_PRICE_ID` VARCHAR(50) NOT NULL,
	`COIN_ID` VARCHAR(50) NOT NULL,
	`UNIT_PRICE` DECIMAL(15, 2) NULL,
	`TRADE_DATE` DATE NULL,
	`HIGH_PRICE` DECIMAL(15, 2) NULL,
	`LOW_PRICE` DECIMAL(15, 2) NULL,
	`BUY_QUANTITY` DECIMAL(15, 2) NULL,
	`SELL_QUANTITY` DECIMAL(15, 2) NULL,
    `CREATED_AT` DATETIME NULL,
	`UPDATED_AT` DATETIME NULL,
	PRIMARY KEY (`CLOSING_PRICE_ID`),
	FOREIGN KEY (`COIN_ID`) REFERENCES `COIN`(`COIN_ID`) ON DELETE CASCADE
);


-- SKILL 데이터 삽입
INSERT INTO `SKILL` (`SKILL_ID`, `STACK`, `CREATED_AT`, `UPDATED_AT`) VALUES
(UUID(), 'HTML', NOW(), NOW()),
(UUID(), 'CSS', NOW(), NOW()),
(UUID(), 'JS', NOW(), NOW()),
(UUID(), 'React', NOW(), NOW()),
(UUID(), 'VueJS', NOW(), NOW()),
(UUID(), 'TypeScript', NOW(), NOW()),
(UUID(), 'NextJS', NOW(), NOW()),
(UUID(), 'NodeJS', NOW(), NOW()),
(UUID(), 'Java', NOW(), NOW()),
(UUID(), 'SpringBoot', NOW(), NOW()),
(UUID(), 'Python', NOW(), NOW()),
(UUID(), 'Django', NOW(), NOW()),
(UUID(), 'MariaDB', NOW(), NOW()),
(UUID(), 'MySQL', NOW(), NOW()),
(UUID(), 'PostgreSQL', NOW(), NOW()),
(UUID(), 'FireBase', NOW(), NOW()),
(UUID(), 'Kotlin', NOW(), NOW()),
(UUID(), 'Swift', NOW(), NOW()),
(UUID(), 'Flutter', NOW(), NOW()),
(UUID(), 'React-Native', NOW(), NOW());